#端口
server:
  port: 8081
#spring
spring:
  profiles:
    active: dev
  devtools:
    restart:
      #热部署开关
      enabled: true
      #指定热部署的目录
      additional-paths: src/main/java
      #指定目录不更新
      exclude: test/**
  #资源访问
  mvc:
    static-path-pattern: /static/**
# 显示sql
logging:
  level:
    com.sm.graduation.*: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

fabric:
  network:
    channelName: mychannel
    configPath: /path/to/fabric/config
  user:
    mspId: Org1MSP
    privateKeyPath: /path/to/private/key
    certificatePath: /path/to/certificate
  peers:
    - name: peer0.org1.example.com
      url: grpc://localhost:7051

